# Generated by Django 3.2.3 on 2022-11-13 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('V1', models.FloatField()),
                ('V2', models.FloatField()),
                ('V3', models.FloatField()),
                ('V4', models.FloatField()),
                ('V5', models.FloatField()),
                ('V6', models.FloatField()),
                ('V7', models.FloatField()),
                ('V8', models.FloatField()),
                ('V9', models.FloatField()),
                ('V10', models.FloatField()),
                ('V11', models.FloatField()),
                ('V12', models.FloatField()),
                ('V13', models.FloatField()),
                ('V14', models.FloatField()),
                ('V15', models.FloatField()),
                ('V16', models.FloatField()),
                ('V17', models.FloatField()),
                ('V18', models.FloatField()),
                ('V19', models.FloatField()),
                ('V20', models.FloatField()),
                ('V21', models.FloatField()),
                ('V22', models.FloatField()),
                ('V23', models.FloatField()),
                ('V24', models.FloatField()),
                ('V25', models.FloatField()),
                ('V26', models.FloatField()),
                ('V27', models.FloatField()),
                ('V28', models.FloatField()),
                ('Amount', models.FloatField()),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='predict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.TextField()),
                ('class_predicted', models.IntegerField()),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('featuresid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.features')),
            ],
            options={
                'db_table': 'predict',
            },
        ),
    ]
