# Generated by Django 3.2.3 on 2022-11-13 01:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='probability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=None), default=None, size=None),
        ),
    ]
